/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-23 01:03:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729137804000L));
    _jspx_dependants.put("jar:file:/D:/Java풀스택/포트폴리오%20제작/새%20폴더/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tenbyten/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>tenbyten</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/tenbyten/css/member/joinForm.css\">\r\n");
      out.write("	<script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"script/member.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"showMessage()\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"Member\" method=\"post\" name=\"frm\">\r\n");
      out.write("    <input type=\"hidden\" name=\"command\" value=\"join\">\r\n");
      out.write("    <h3>필수항목</h3>\r\n");
      out.write("        <table id=\"Required\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<input type=\"text\" name=\"userid\" placeholder=\"아이디\" >\r\n");
      out.write("                	<input type=\"hidden\" name=\"reid\" size=\"20\"> \r\n");
      out.write("              		<input type=\"button\" id=\"idCheck-btn\" value=\"중복 체크\" onclick=\"idCheck()\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	3~15자의 영문/숫자를 조합하여 입력\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><input type=\"password\" name=\"pwd\" id=\"pwd\" placeholder=\"비밀번호\" ></td>\r\n");
      out.write("            	<td>8-10자의 영문/숫자를 조합하여 입력</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><input type=\"password\" name=\"pwd_check\" id=\"pwd_check\" placeholder=\"비밀번호 확인\" onkeyup=\"pwdCheck()\"></td>\r\n");
      out.write("                <td id=\"checkText\"></td>    \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            	 <td>\r\n");
      out.write("                    <input type=\"text\" class=\"phone-input\" name=\"phone1\" maxlength=\"3\" placeholder=\"전화번호\">\r\n");
      out.write("                    <input type=\"text\" class=\"phone-input\" name=\"phone2\" maxlength=\"4\" >\r\n");
      out.write("                    <input type=\"text\" class=\"phone-input\" name=\"phone3\" maxlength=\"4\" >\r\n");
      out.write("                </td>\r\n");
      out.write("                <td></td>              \r\n");
      out.write("            </tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"radio\" name=\"admin\" value=\"0\" onchange=\"toggleAdminCodeInput()\" checked=\"checked\" >일반회원\r\n");
      out.write("					<input type=\"radio\" name=\"admin\" value=\"1\" onchange=\"toggleAdminCodeInput()\" >관리자\r\n");
      out.write("				</td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("            <tr id=\"admin_view\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"admin_code\" placeholder=\"인증번호 6자리를 입력하세요\">      \r\n");
      out.write("                </td>\r\n");
      out.write("                 <td name=\"admin_text\">\r\n");
      out.write("                 	<button type=\"button\" name=\"admin_btn\" onclick=\"admincheck()\">확인</button>\r\n");
      out.write("                 	<input type=\"hidden\" name=\"abmin_check\" value=\"0\">\r\n");
      out.write("                 </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h3>선택항목</h3>\r\n");
      out.write("		<table id=\"Select\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><input type=\"text\" id=\"username\" name=\"username\" placeholder=\"성명\"></td>\r\n");
      out.write("            	<td>한글 15자, 영문 30자까지 가능합니다</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><input type=\"text\" id=\"birth\" name=\"birth\" placeholder=\"생년월일\"></td>\r\n");
      out.write("                <td>8자리로 입력하십시오.</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <input type=\"submit\" class=\"submit-btn\" value=\"회원가입 신청하기\" onclick=\"return joinCheck()\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
