/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-22 06:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/common.css\"> \r\n");
      out.write("	    <script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js\"></script>\r\n");
      out.write("	    \r\n");
      out.write("		\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <hr class=\"gray_hr\">\r\n");
      out.write("        <ul id=\"footer_head\">\r\n");
      out.write("            <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("            <li><a href=\"#\">채용정보</a></li>\r\n");
      out.write("            <li><b><a href=\"#\">이용약관</a></b></li>\r\n");
      out.write("            <li><b><a href=\"#\">개인정보 처리방침</a></b></li>\r\n");
      out.write("            <li><b><a href=\"#\">청소년 보호정책</a></b></li>\r\n");
      out.write("            <li><a href=\"#\">제휴/광고</a></li>\r\n");
      out.write("            <li><a href=\"#\">입점문의</a></li>\r\n");
      out.write("            <li><a href=\"#\">매장안내</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <hr class=\"gray_hr\">\r\n");
      out.write("        <div id=\"footer_div\">\r\n");
      out.write("            <div id=\"footer_1\">\r\n");
      out.write("                <img src=\"img/footer_logo.png\" alt=\"footer_logo\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"footer_2\">\r\n");
      out.write("                <h4>(주)텐바이텐</h4>\r\n");
      out.write("                <p>대표이사 : 송승훈 / 서울특별시 서초구 서초대로 398 BNK디지털타워 19층 텐바이텐</p>\r\n");
      out.write("                <p>사업자등록번호 : 211-87-00620 / 통신판매업 신고 : 2024-서울서초-1568</p>\r\n");
      out.write("                <p>전화번호 : 1644-6030 / E-mail : customer@10x10.co.kr</p>\r\n");
      out.write("                <p>개인정보보호책임자 : 김동철 / 소비자피해보상보험 SGI 서울보증 </p>\r\n");
      out.write("                <p>호스팅서비스:㈜텐바이텐</p>\r\n");
      out.write("                <p>사이트 내 판매 상품 중 일부는 ㈜텐바이텐에 입점한 개별판매자가 판매하는 상품이 포함되어 있습니다. 해당 상품의 경우\r\n");
      out.write("                    ㈜텐바이텐은 통신판매중개자로서 판매 당사자가 아니며, 상품정보 및 거래 등에 대한 책임을 지지 않습니다.</p>\r\n");
      out.write("                <p>COPYRIGHT © TENBYTEN ALL RIGHTS RESERVED.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"footer_3\">\r\n");
      out.write("                <div id=\"footer_icon\">\r\n");
      out.write("                    <img src=\"img\\icon\\icon_sns_instagram.png.crdownload\" alt=\"sns\">\r\n");
      out.write("                    <img src=\"img\\icon\\icon_sns_facebook.png.crdownload\" alt=\"sns\">\r\n");
      out.write("                    <img src=\"img\\icon\\icon_sns_you.png.crdownload\" alt=\"sns\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <div id=\"footer_cscenter\">\r\n");
      out.write("                        <h4>고객센터 바로가기 ></h4>\r\n");
      out.write("                        <p><span>운영시간</span>오전 10시 ~ 오후 5시(주말,공휴일 휴무)</p>\r\n");
      out.write("                        <p><span>점심시간</span>오후 12시 30분 ~ 오후 1시 30분</p>                \r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
