/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-22 06:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729137804000L));
    _jspx_dependants.put("jar:file:/D:/Java풀스택/포트폴리오%20제작/새%20폴더/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tenbyten/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/common.css\"> \r\n");
      out.write("	    <script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js\"></script>\r\n");
      out.write("	    \r\n");
      out.write("        <script src=\"script/js/mainCategory.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- 최상단 -->\r\n");
      out.write("	    <div id=\"headerTop\">\r\n");
      out.write("	        <div class=\"headUser\">\r\n");
      out.write("	            <ul>\r\n");
      out.write("	            	\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	                <li class =\"userSelect\">알림</li>\r\n");
      out.write("	                <li class =\"userSelect\">주문/배송</li>\r\n");
      out.write("	                <li class =\"userSelect\">장바구니</li>\r\n");
      out.write("	            </ul>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- 헤더 -->\r\n");
      out.write("	    <header>\r\n");
      out.write("	        <div id=\"header_logo\"><a href=\"#\"><img src=\"img/header_logo.png\"></a></div>\r\n");
      out.write("	        <div id=\"header_cate\"> \r\n");
      out.write("	            <ul>\r\n");
      out.write("	                <li><a href=\"#\">2024 텐텐다꾸</a></li>\r\n");
      out.write("	                <li><a href=\"#\">프리오더</a></li>\r\n");
      out.write("	                <li><a href=\"#\">신상품</a></li>\r\n");
      out.write("	                <li><a href=\"#\">베스트</a></li>\r\n");
      out.write("	                <li><a href=\"#\">할인특가</a></li>\r\n");
      out.write("	                <li><a href=\"#\">기획전</a></li>\r\n");
      out.write("	                <li><a href=\"#\">브랜드</a></li>\r\n");
      out.write("	            </ul>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div id=\"header_search\">\r\n");
      out.write("	            <input type=\"text\" id=\"search\" name=\"search\" placeholder=\" 12달 모두 행복할 스누피 칫솔 신상 출시\">\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </header>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- 카테고리 네비게이션 -->\r\n");
      out.write("	    <nav>\r\n");
      out.write("	        <ul>\r\n");
      out.write("	            <li name =\"cate_1\"><a href=\"category.html\">디자인문구</a></li>\r\n");
      out.write("	            <li name =\"cate_2\"><a href=\"#\">디지털/핸드폰</a></li>\r\n");
      out.write("	            <li class=\"line\" name =\"cate_3\"><a href=\"#\">디자인가전</a></li>\r\n");
      out.write("	            <li name =\"cate_4\"><a href=\"#\">가구/수납</a></li>\r\n");
      out.write("	            <li name =\"cate_5\"><a href=\"#\">패브릭/생활</a></li>\r\n");
      out.write("	            <li name =\"cate_6\"><a href=\"#\">데코/조명</a></li>\r\n");
      out.write("	            <li name =\"cate_7\"><a href=\"#\">키친</a></li>\r\n");
      out.write("	            <li name =\"cate_8\"><a href=\"#\">푸드</a></li>\r\n");
      out.write("	            <li name =\"cate_9\"><a href=\"#\">패션의류</a></li>\r\n");
      out.write("	            <li name =\"cate_10\"><a href=\"#\">패션잡화</a></li>\r\n");
      out.write("	            <li name =\"cate_11\"><a href=\"#\">뷰티</a></li>\r\n");
      out.write("	            <li name =\"cate_12\" class=\"line\"><a href=\"#\">주얼리/시계</a></li>\r\n");
      out.write("	            <li name =\"cate_13\"><a href=\"#\">Cat&amp;Dog</a></li>\r\n");
      out.write("	            <li name =\"cate_14\"><a href=\"#\">토이/취미</a></li>\r\n");
      out.write("	            <li name =\"cate_15\"><a href=\"#\">캠핑</a></li>\r\n");
      out.write("	        </ul>\r\n");
      out.write("	    </nav>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- 카테고리 메뉴            ========================================== -->\r\n");
      out.write("	    <div id=\"wrap\">\r\n");
      out.write("	        <div class=\"subWrap\" id=\"cate_1\">\r\n");
      out.write("	            <div class=\"subWrapUnit floatLeft\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='category.html'>다이어리/플래너</a></li>\r\n");
      out.write("	                    <li><a href='#'>다이어리 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>오거나이저</a></li>\r\n");
      out.write("	                    <li><a href='#'>스케줄러/플래너</a></li>\r\n");
      out.write("	                    <li><a href='#'>달력</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>노트/메모지</a></li>\r\n");
      out.write("	                    <li><a href='#'>베이직 노트 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>양장 노트</a></li>\r\n");
      out.write("	                    <li><a href='#'>스프링 노트</a></li>\r\n");
      out.write("	                    <li><a href='#'>미니노트</a></li>\r\n");
      out.write("	                    <li><a href='#'>독서노트</a></li>\r\n");
      out.write("	                    <li><a href='#'>단어장 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>수첩</a></li>\r\n");
      out.write("	                    <li><a href='#'>메모지</a></li>\r\n");
      out.write("	                    <li><a href='#'>기타 노트</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>데코레이션 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>스탬프</a></li>\r\n");
      out.write("	                    <li><a href='#'>스티커 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>테이프/다이모</a></li>\r\n");
      out.write("	                    <li><a href='#'>펀치</a></li>\r\n");
      out.write("	                    <li><a href='#'>선물 포장</a></li>\r\n");
      out.write("	                    <li><a href='#'>장식오너먼트</a></li>\r\n");
      out.write("	                    <li><a href='#'>포스터</a></li>\r\n");
      out.write("	                    <li><a href='#'>뱃지/와펜</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>필기류/필통</a></li>\r\n");
      out.write("	                    <li><a href='#'>필기구 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>고급필기류 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>필통</a></li>\r\n");
      out.write("	                    <li><a href='#'>필기구 브랜드샵 N</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>포토앨범/레코드북</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>카드/편지/봉투</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>파일/바인더</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>사무용품</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>데스크 정리/보관</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>디지털 문구 N</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>해외디자인문구</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>캐릭터 문구</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>미술도구</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>BOOK</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>SALE</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>EVENT</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	\r\n");
      out.write("	        <div class=\"subWrap floatLeft\" id=\"cate_2\">\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>핸드폰</a></li>\r\n");
      out.write("	                    <li><a href='#'>갤럭시 H N</a></li>\r\n");
      out.write("	                    <li><a href='#'>아이폰 N</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>핸드폰 주변기기 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>갤럭시 케이스 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>애플 케이스 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>기타 핸드폰 케이스</a></li>\r\n");
      out.write("	                    <li><a href='#'>애플 보호필름</a></li>\r\n");
      out.write("	                    <li><a href='#'>갤럭시 보호필름</a></li>\r\n");
      out.write("	                    <li><a href='#'>기타 핸드폰 보호필름</a></li>\r\n");
      out.write("	                    <li><a href='#'>충전기</a></li>\r\n");
      out.write("	                    <li><a href='#'>케이블</a></li>\r\n");
      out.write("	                    <li><a href='#'>거치대/홀더</a></li>\r\n");
      out.write("	                    <li><a href='#'>기타 주변기기</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>태블릿 PC</a></li>\r\n");
      out.write("	                    <li><a href='#'>갤럭시탭</a></li>\r\n");
      out.write("	                    <li><a href='#'>갤럭시탭 액세서리</a></li>\r\n");
      out.write("	                    <li><a href='#'>아이패드</a></li>\r\n");
      out.write("	                    <li><a href='#'>아이패드 액세서리 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>태블릿PC 거치대</a></li>\r\n");
      out.write("	                    <li><a href='#'>기타 태블릿PC 액세...</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>PC/노트북</a></li>\r\n");
      out.write("	                    <li><a href='#'>노트북</a></li>\r\n");
      out.write("	                    <li><a href='#'>PC</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>PC/노트북 주변기기</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>마우스/키보드</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>game shop</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>스마트워치</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>IoT/생활</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>카메라</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>영상기기</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>음향기기</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>선물샵</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>SALE</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>EVENT</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	\r\n");
      out.write("	        \r\n");
      out.write("	        <div class=\"subWrap floatRight\" id=\"cate_9\">\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>여성 아우터</a></li>\r\n");
      out.write("	                    <li><a href='#'>코트</a></li>\r\n");
      out.write("	                    <li><a href='#'>점퍼</a></li>\r\n");
      out.write("	                    <li><a href='#'>야상</a></li>\r\n");
      out.write("	                    <li><a href='#'>자켓</a></li>\r\n");
      out.write("	                    <li><a href='#'>패딩</a></li>\r\n");
      out.write("	                    <li><a href='#'>레인코트 N</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>여성 드레스</a></li>\r\n");
      out.write("	                    <li><a href='#'>롱/미디 원피스 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>미니 원피스</a></li>\r\n");
      out.write("	                    <li><a href='#'>레이어드 원피스</a></li>\r\n");
      out.write("	                    <li><a href='#'>민소매 원피스</a></li>\r\n");
      out.write("	                    <li><a href='#'>정장 원피스</a></li>\r\n");
      out.write("	                    <li><a href='#'>생활한복 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>니트 원피스</a></li>\r\n");
      out.write("	                    <li><a href='#'>셀프웨딩 드레스 N</a></li>                    \r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>여성 상의</a></li>\r\n");
      out.write("	                    <li><a href='#'>스웨트셔츠 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>후드 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>후드집업</a></li>\r\n");
      out.write("	                    <li><a href='#'>티셔츠 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>니트/조끼</a></li>\r\n");
      out.write("	                    <li><a href='#'>가디건 N</a></li>\r\n");
      out.write("	                    <li><a href='#'>셔츠/블라우스</a></li>                    \r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>여성 하의</a></li>\r\n");
      out.write("	                    <li><a href='#'>스커트</a></li>\r\n");
      out.write("	                    <li><a href='#'>팬츠 H</a></li>\r\n");
      out.write("	                    <li><a href='#'>레깅스</a></li>                    \r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"subWrapUnit\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>남성 아우터</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>남성 상의</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>남성 하의</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>유아동 의류</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>라운지웨어 H</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>비치웨어 N</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>선물샵</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>SALE</a></li>\r\n");
      out.write("	                    <li class=\"bold\"><a href='#'>EVENT</a></li>                    \r\n");
      out.write("	                </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <!-- 카테고리 메뉴            ========================================== -->\r\n");
      out.write("	    <hr class=\"gray_hr\">\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Views/header.jsp(21,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            			<li class =\"userSelect\"><a href=\"Member?command=login_form\">로그인</a>/<a href=\"Member?command=join_form\">회원가입</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Views/header.jsp(24,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            		<li class =\"userSelect\"><a href=\"Member?command=user\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>님  <a href=\"main?command=logout\">로그아웃</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
